---

- name: copy 90 routing sysctl
  template:
    src: 90-routing-sysctl.conf.j2
    swst: /etc/sysctl.d/90-routing-sysctl.conf

- name: copy daemons frr
  template:
    src: daemons.j2
    dest: /etc/frr/daemons
    notify: restart frr service