---

- name: make directory nfs_1 and nfs_2
  block:
    - name: make directory nfs_1
      file:
        path: /home/it/"{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
        recurse: yes
      loop:
        - nfs_1
        - nfs_2



