---

- name: Locate grafana
  copy:
    src: "{{ item }}"
    dest: "{{ grafana.download_dir | defaults(grafana_defaults.download_dir) }}"
    mode: 0755
#    remote_src: true
  with_items:
    - "{{ grafana.rpm | defaults(grafana_defaults.rpm) }}.rpm"

- name: install grafana
  import_role:
    name: common/install_packages
  vars:
    package_action: "install"
    package_list:
      - "{{ grafana.download_dir | defaults(grafana_defaults.download_dir) }}/{{ grafana.rpm | defaults(grafana_defaults.rpm) }}.rpm"
