---

- name: Check if output directory exists
  stat:
    path: /home/it/frr
  register: output_folder

- name: Create directory and download frr, and libyang
  block:
    - name: Create directory
      file:
        path: /home/it/frr
        state: directory
        owner: root
        group: root
        mode: 0755
        recurse: yes
      when: output_folder.stat.exists == false

    - name: Download frr
      get_url:
        url: https://github.com/FRRouting/frr/releases/download/frr-7.0/frr-7.0-01.el7.webinar_2.x86_64.rpm
        dest: /home/it/frr


    - name: Copy libyang
      copy:
        src: /home/it/1/libyang-0.16.111-0.x86_64.rpm
        dest: /home/it/frr

