---
- name: adding a firewall rules
  block:
    - name: allow icmp
      firewalld:
        zone: public
        state: present
        permanent: yes
        icmp_block_inversion: no

    - name: allow icmp
      firewalld:
        zone: public
        state: enabled
        permanent: yes
        protocols: ospf
    notify: reload firewalld