---

- name: 'PREREQUISITES | prepare to install Zabbix Server'
  import_tasks: prereq.yml

- name: 'INSTALL | install Zabbix Server'
  import_tasks: install.yml

- name: 'CONFIGURATE | Configurate Zabbix Server'
  import_tasks: config.yml
