---
- hosts: all
  gather_facts: False
  roles:
#    - os/firewalld
#    - os/NIC_teaming
#    - os/dhcp
#    - os/NFS-Server
#    - os/dns
#    - monitoring/prometheus
#    - monitoring/grafana
#    - os/logrotate
    - os/unifi




