---
- hosts: all
  gather_facts: False
  roles:
    - os/firewalld
    - os/selinux
#    - os/NIC_teaming
#    - os/dhcp
#    - os/NFS-Server
#    - os/dns
    - monitoring/prometheus
    - monitoring/snmp_exporter
    - monitoring/grafana
    - os/logrotate
#    - os/unifi
#    - common/install_packages




