---

- name: copy config files
  block:
    - name: copy on R1
      template:
        src: ifcfg-team0_r1.j2
        dest: "{{ team.dir }}/ifcfg-team0"
      when: " 'R1' in inventory_hostname"

    - name: copy on R2
      template:
        src: ifcfg-team0_r2.j2
        dest: "{{ team.dir }}/ifcfg-team0"
      when: " 'R2' in inventory_hostname"

    - name: copy on R3
      template:
        src: ifcfg-team0_r3.j2
        dest: "{{ team.dir }}/ifcfg-team0"
      when: " 'R3' in inventory_hostname"

